### ISSUE TITLE
godot-4 branch: Stopping debug mode in editor often does not close gdcefSubProcess.exe on Windows 11

### ISSUE THREAD

**Issue by TheSilentFog** [Lecrapouille/gdcef#41] opened 2024-01-25 18:51 UTC
I just discovered that running gdcef on windows 11 from the editor and subsequently stopping the debug run often results in the browser background process to not close at all.

This behaviour seems to be unconsistent from what I do with the open browser inside the godot run window.

I had an instance of this problem where after even some failed runs on godot, due to code errors, there were 5 ghost browser processes using almost all of my cpu.
I had to kill them one by one on the task manager.

Shouldn't be there, inside the browser process, a ping system which checks if the godot process that created it is still alive to prevent edge cases?

I was trying things out on the 2D demo project.

![image](https://github.com/Lecrapouille/gdcef/assets/148537111/a895e709-f7b9-4d7d-aa32-2d1e90e13ee2)

**Comment by Lecrapouille** [comment] 2024-01-25 21:50
@TheSilentFog, in nominal cases, what the operating system, if you see multiple cef processes, it's normal: CEF do many forks of itself (Firefox also do the same things).

If these processes are not correctly killed this is an issue. I checked on Linux I do not have this issue. @raphipod can you check (I do not have windows).

**Comment by Pastew** [comment] 2024-06-16 11:06
Hello,
I encountered the same problem on Windows 10.
![image](https://github.com/Lecrapouille/gdcef/assets/5671416/963059bf-52ff-4588-8f99-f719d3774049)


Reproduce steps are easy:
1. Hit Play in Godot, wait until browser loads website.
2. Hit Stop.
3. You should have 1 ghost process in Task Manager

Repeat steps to get more ghost processes.

**Comment by raphipod** [comment] 2024-06-16 13:25
> @TheSilentFog, in nominal cases, whatever the operating system you are using, if you see multiple cef processes, this is normal: CEF creates many forks of itself (Firefox also do the same things).
> 
> If these processes are not correctly killed, this is an issue. I checked on Linux, I do not have this issue. @raphipod can you check (I do not have windows).

That's correct. It works properly on Linux, weirdly enough.

I have yet to test it on Windows specifically, but on my prior debug tests I also noted this and thought it was normal as CEF uses multiple threads for rendering/drawing, audio, network etc.

AFAIK, the CefShutdown() function should be executed in the thread where CefInitialize() should've been called beforehand, so that all subprocesses can get notified.

@TheSilentFog do/did you have an antivirus running in the background? It could be that some subprocesses are getting flagged/quarantined by an AV...

**Comment by Lecrapouille** [comment] 2024-06-17 07:06
I know That GDCef instance is not destroyed. Maybe because Godot is still using it when inside the editor (ref counter). It is released when Godot ends. On Linux forks are killed I guess artificially. So maybe in Windows there is not such security

**Comment by Pastew** [comment] 2024-06-21 13:30
1. I noticed it doesn't happen every time. But when it happens, after I hit `Play` button in Godot I see many `gdcefSubProcess`es under Godot process:
![image](https://github.com/Lecrapouille/gdcef/assets/5671416/dade16ea-a19f-4471-9d6d-278184a9f8b6)

And after I hit `Stop` one of them seems to be somehow detached from parent process and stays alive forever in "Background processes" category in Task Manager.
![image](https://github.com/Lecrapouille/gdcef/assets/5671416/0d4a7e49-dbfc-4df1-a9f6-c3b1d65b724e)

2. Closing Godot Editor does not kill this `gdcefSubProcess`.

**Comment by pimhakkert** [comment] 2024-07-23 21:18
I concur, it does not happen every time, but it can quickly stack up. Has anyone had issues with this regarding a production build? If so then we need to expedite a fix. My PC (windows) came to a grinding halt because these subprocesses were taking up my entire CPU during development.

**Comment by Lecrapouille** [comment] 2024-09-23 23:36
Yes this is a real issue @face-hh https://youtu.be/37ISfJ2NSXQ?feature=shared&t=446 noticed it :) @eliopark-nsuslab have you idea ? I think probably a conflict between Godot's RefCount and CEF's RefCount. On Linux I do not have such zombies exe running.

**Comment by Lecrapouille** [comment] 2024-12-03 00:19
I tried on the new commit where I manage better the shutdown of browsers. I see nothing special. And yes CEF seems to spawn several processes, this is how it works but hard for me to say if this happens the same thing for other applications based on CEF

**Comment by eliopark-nsuslab** [comment] 2024-12-03 00:25
> Yes this is a real issue @face-hh https://youtu.be/37ISfJ2NSXQ?feature=shared&t=446 noticed it :) @eliopark-nsuslab have you idea ? I think probably a conflict between Godot's RefCount and CEF's RefCount. On Linux I do not have such zombies exe running.

@Lecrapouille I've been having the same problem, but haven't found a solution yet.

**Comment by Lecrapouille** [comment] 2024-12-03 00:35
@eliopark-nsuslab Can you try my latest commit and tell me if this fix or not

**Comment by Lecrapouille** [comment] 2024-12-03 00:47
https://github.com/cefsharp/CefSharp/issues/1075

**Comment by Lecrapouille** [comment] 2024-12-03 00:48
I have the same thing on Linux but now I better close Godot nodes I guess.

**Comment by Lecrapouille** [comment] 2024-12-03 01:13
@eliopark-nsuslab cannot you join the discord ?

**Comment by Lecrapouille** [comment] 2024-12-03 23:41
I'm closing since I think I fixed it. Open a new issue if this is not the case

**Closed by Lecrapouille** 2024-12-03 23:41 UTC

**Comment by Pastew** [comment] 2024-12-04 06:48
@Lecrapouille are there artifacts available to download? I can't find it in github actions

**Comment by Lecrapouille** [comment] 2024-12-04 07:01
Not yet released i'll try to inclure download management and javascript bindings

**Comment by Lecrapouille** [comment] 2024-12-07 11:30
@Pastew @eliopark-nsuslab The 0.14 version has been released. Tell me if better if not
